"use client";

import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
{
  /*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Header />
          <div className="absolute inset-0 z-0">
            <Image
              className=" object-cover w-full opacity-30"
              src="/upperBackground.jpg"
              fill
              style={{
                objectFit: "cover",
              }}
              alt="Background Image"
              loading="lazy"
            />

            <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent"></div>
          </div>

          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
